vm_settings: &vm_settings
  working_directory: ~/app
  docker:
    - image: circleci/node:latest

version: 2
jobs:
  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/python:2.7
    steps:
      - attach_workspace:
          at: ~/app/build

      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: AWS Sync
          command: aws --region eu-west-1 s3 mv ./build s3://neetamadahar.com/ --exclude yoga/ --acl public-read --exact-timestamps --delete || return 1

  checkout:
    <<: *vm_settings
    steps:
      - checkout

      - persist_to_workspace:
          root: ~/app
          paths:
            - .

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - checkout
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
